enum ScreenNames {
  HOME = "Home",
  PROFILE = "Profile",
  CHAT = "Chat",
  MYADS = "MyAds",
  AUTHENTICATION = "Authentication",
  ADPOST = "AdPost",
  EDITPROFILE = "EditProfile",
  TABHOME = "TabHome",
  TABAUTHENTICATION = "TabAuthentication",
  TABADPOST = "TabAdPost",
  HOMESTACK = "homeStack",
  ADS = "Ads",
  CATEGORIES = "Categories",
  DETAILS = "Details",
  SUBCATEGORIES = "SubCategories",
  LOCATION = "Location",
  EMAIL_VERIFICATION = "EmailVerification",
  CHANGE_PASSWORD = "ChangePassword",
  SETTINGS = "Settings",
  PRIVACY = "Privacy",
  MANAGE_ACCOUNT = "ManageAccount",
  CHANGE_LANGUAGE = "ChangeLanguage",
  FAVORITES = "Favorites",
  PERSONAL_ADS = "PersonalAds",
}

export default ScreenNames;
